### ISSUE TITLE
Reject or approve application

### ISSUE THREAD

**Issue by datlechin** [FPOLY-HCM/WEB3014#65]
Reject or approve application in account

Add 2 buttons approve and reject in applications list

**Comment by dang-khai** [comment]
này bên admin hay account z

**Comment by dang-khai** [comment]
ụa reject thì nó đi đâu approve thì nó đi đâu

**Comment by datlechin** [comment]
Về trang trước

**Comment by dang-khai** [comment]
có đổi gì trong DB ko

**Comment by datlechin** [comment]
update status, sử dụng enum

vd như:

```php
$application->update(['status' => ApplicationStatus::REJECTED])
